person:
  name: wjy
  age: 3
  happy: false
  birth: 2000/02/21
  maps: {k1: v1,k2: v2}
  lists:
    - code
    - music
    - boy
  dog:
    name: 来福
    age: 3

#server:
  #port: 8084
#spring:
  #profiles:
    #active: dev
#---
#server:
  #port: 8086
#spring:
  #profiles: test
#---
#server:
  #port: 8085
#spring:
  #profiles: dev
